### ISSUE TITLE
Client is already terminated

### ISSUE THREAD

**Issue by AliFreeGuy** [EverythingSuckz/TG-FileStreamBot#146]
When I stop or kill the project and up it again, it gives this error:

ConnectionError: Client is already terminated
[10/05/2024 16:44:03][server][INFO] ==> Initializing..
[10/05/2024 16:44:03][server][INFO] ==> Added routes
[10/05/2024 16:44:03][root][INFO] ==> Initializing Telegram Bot
[10/05/2024 16:44:07][root][ERROR] ==> name 'filters' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/WebStreamer/__main__.py", line 64, in <module>
    loop.run_until_complete(cleanup())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/WebStreamer/__main__.py", line 54, in cleanup
    await StreamBot.stop()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/stop.py", line 65, in stop
    await do_it()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/utilities/stop.py", line 61, in do_it
    await self.terminate()
  File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/auth/terminate.py", line 40, in terminate
    raise ConnectionError("Client is already terminated")
ConnectionError: Client is already terminated

**Comment by DeekshithSH** [comment]
try again installing pyrogram

**Comment by DeekshithSH** [comment]
Run this command 
```sh
pip3 install --upgrade --force-reinstall pyrogram
```

**Comment by AliFreeGuy** [comment]
![image](https://github.com/EverythingSuckz/TG-FileStreamBot/assets/75535732/a34123d3-fe9b-41ef-8990-31660fdc6d68)

not working :(

**Comment by AliFreeGuy** [comment]
The requests should be added to the requirements
