### ISSUE TITLE
quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by DeekshithSH** [EverythingSuckz/TG-FileStreamBot#32]
Get Error Like This
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/user/project/git/TelegramBot/TG-FileStreamBot/WebStreamer/bot/plugins/stream.py", line 42, in media_receive_handler
    stream_link = f"{Var.URL}{log_msg.message_id}/{quote_plus(get_name(m))}?hash={get_hash(log_msg)}"
  File "/usr/lib/python3.8/urllib/parse.py", line 867, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/usr/lib/python3.8/urllib/parse.py", line 851, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.8/urllib/parse.py", line 876, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```
Happend with Video
Generated Link for Photo why This Happening Both Video and Photo Don't have FileName

**Comment by eyMarv** [comment]
@DeekshithSH Telegram does not provide file_name for photos sent with compression.

**Comment by DeekshithSH** [comment]
Telling Same thing When sending Photo The Bot Generated Link
When Sending Video The Bot Return Error
For Video and Audio Telegram Don't Provide File Name
