### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by lukemin** [EverythingSuckz/TG-FileStreamBot#33]
-------------------- Initializing Telegram Bot --------------------
------------------------------ DONE ------------------------------

---------------------- Initializing Clients ----------------------
No additional clients found, using default client
------------------------------ DONE ------------------------------
--------------------- Initalizing Web Server ---------------------
------------------------------ DONE ------------------------------

------------------------- Service Started -------------------------
                        bot =>> ruvdsbot
                        server ip =>> 0.0.0.0
------------------------------------------------------------------
[01/03/2022 13:55:37][ERROR] => 'NoneType' object has no attribute 'mention'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/TG-FileStreamBot/WebStreamer/bot/plugins/start.py", line 12, in start
    f'Hi {m.from_user.mention(style="md")}, Send me a file to get an instant stream link.'
AttributeError: 'NoneType' object has no attribute 'mention'

It works when I send files directly to the bot, but does not works when I send files to the bin_channel

my .env is as below
API_ID=1****
API_HASH=ea8e8e41812b8d*****50b2c1
BOT_TOKEN=52****00:AAF9or7yt4****TIcxh0MQuAU
BIN_CHANNEL=-100165*****
PORT=9999
FQDN=tg.19841106.xyz
HAS_SSL=False

**Comment by lukemin** [comment]
FIXIT
