### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by kinza904** [EverythingSuckz/TG-FileStreamBot#66]
Getting this Error:
```
resp, reset = await task
File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 460, in _handle_request
reset = await self.finish_response(request, resp, start_time)
File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 614, in finish_response
 await resp.write_eof()
File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_response.py", line 749, in write_eof
await payload.write(self._payload_writer)
File "/usr/local/lib/python3.10/dist-packages/aiohttp/payload.py", line 443, in write
chunk = await self._iter.__anext__()
File "/usr/src/app/WebStreamer/utils/custom_dl.py", line 197, in yield_file
r = await media_session.invoke(
File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 381, in invoke
return await self.invoke(query, retries - 1, timeout)
File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 381, in invoke
return await self.invoke(query, retries - 1, timeout)
File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 381, in invoke
return await self.invoke(query, retries - 1, timeout)
[Previous line repeated 2 more times]
File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 374, in invoke
 raise e from None
 File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 361, in invoke
 return await self.send(query, timeout=timeout)
 File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 315, in send
raise e
File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 312, in send
await self.connection.send(payload)
File "/usr/local/lib/python3.10/dist-packages/pyrogram/connection/connection.py", line 83, in send
 raise OSError(e)
OSError: Value after * must be an iterable, not NoneType
[ERROR] => Unhandled exception
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 514, in start
resp, reset = await task
```

**Comment by EverythingSuckz** [comment]
Try running it on python 3.9.x
